name: M3U8 Download

on:
  workflow_dispatch:
    inputs:
      link:
        description: 'Link'
        required: true
      slug:
        description: 'Slug'
        required: true
      token:
        description: 'Token'
        required: true
      page:
        description: 'Pages'
        required: true
      account:
        description: 'Account'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg aria2 curl jq
          python3 -m pip install -U yt-dlp

      - name: Download M3U8 by segments
        run: |
      
          URL="${{ github.event.inputs.link }}"
      
          echo "Getting real m3u8..."
          M3U8=$(yt-dlp -g "$URL")
      
          echo "M3U8 URL: $M3U8"
      
          BASE=$(dirname "$M3U8")
      
          echo "Base URL: $BASE"
      
          echo "Downloading playlist..."
          curl -L "$M3U8" -o playlist.m3u8
      
          echo "Parsing segments..."
          grep -v '^#' playlist.m3u8 > segments.txt
      
          TOTAL=$(wc -l < segments.txt)
      
          echo "Total segments: $TOTAL"
      
          mkdir -p segments
      
          INDEX=0
      
          while read SEG; do
      
            FILE=$(printf "segments/seg_%05d.ts" $INDEX)
      
            echo "=============================="
            echo "Segment $INDEX / $TOTAL"
            echo "=============================="
      
            if [[ "$SEG" == http* ]]; then
              FULL="$SEG"
            else
              FULL="$BASE/$SEG"
            fi
      
            while true; do
      
              echo "Downloading $FULL"
      
              aria2c \
                --quiet=true \
                --allow-overwrite=true \
                --file-allocation=none \
                --max-tries=1 \
                --connect-timeout=30 \
                --timeout=300 \
                -o "$FILE.tmp" \
                "$FULL"
      
              if [ ! -f "$FILE.tmp" ]; then
                echo "Download failed → wait 60s"
                sleep 60
                continue
              fi
      
              SIZE=$(stat -c%s "$FILE.tmp")
      
              if [ "$SIZE" -lt 50000 ]; then
                echo "Segment too small → retry in 60s"
                rm -f "$FILE.tmp"
                sleep 60
                continue
              fi
      
              ffprobe -v error "$FILE.tmp" >/dev/null 2>&1
      
              if [ $? -ne 0 ]; then
                echo "Segment corrupt → retry in 60s"
                rm -f "$FILE.tmp"
                sleep 60
                continue
              fi
      
              mv "$FILE.tmp" "$FILE"
      
              echo "Segment OK"
      
              break
      
            done
      
            INDEX=$((INDEX+1))
      
          done < segments.txt
      
      
          echo "Creating concat list..."
      
          rm -f list.txt
      
          for f in segments/*.ts; do
            echo "file '$f'" >> list.txt
          done
      
      
          echo "Merging segments..."
      
          ffmpeg \
            -loglevel error \
            -f concat \
            -safe 0 \
            -i list.txt \
            -c copy \
            input_video.mp4
      
      
          echo "Verifying video..."
      
          ffmpeg -v error -i input_video.mp4 -f null - || {
            echo "Video decode error"
            exit 1
          }
      
          echo "Video completed successfully"
          
      - name: Re-Encode & Convert to HLS fMP4 (Strict 5.00s Segments as PNG)
        run: |
          mkdir -p output
          
          # Cập nhật Encode:
          # -r 30 : Ép cố định 30 hình/giây
          # -g 150 -keyint_min 150 : Buộc tạo Keyframe mỗi 150 hình (Chính xác 5 giây sẽ có 1 điểm cắt)
          # -ar 48000 : Ép audio sample rate để cắt file không bị lệch nhịp
          
          ffmpeg -y -stats_period 30 -i input_video.mp4 \
            -map 0:v:0 -map 0:a? \
            -c:v libx264 -pix_fmt yuv420p -profile:v high -level 4.1 -crf 21 -preset medium \
            -maxrate 2500k -bufsize 3500k \
            -r 30 -g 150 -keyint_min 150 -sc_threshold 0 \
            -c:a aac -b:a 96k -ac 2 -ar 48000 -threads 0 \
            -f hls \
            -start_number 10001 \
            -hls_time 5 \
            -hls_list_size 0 \
            -hls_segment_type fmp4 \
            -hls_fmp4_init_filename "${{ github.event.inputs.slug }}-index.png" \
            -hls_segment_filename "output/${{ github.event.inputs.slug }}-index%d.png" \
            "output/${{ github.event.inputs.slug }}.m3u8"
          
          # Kiểm tra xem file m3u8 có được tạo không
          if [ ! -f "output/${{ github.event.inputs.slug }}.m3u8" ]; then
            echo "FFmpeg failed to create m3u8"
            exit 1
          fi

      - name: Deploy to Cloudflare Pages (first)
        id: deploy1
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ github.event.inputs.token }}
          accountId: ${{ github.event.inputs.account }}
          projectName: ${{ github.event.inputs.page }}
          directory: ./output
          branch: ${{ github.event.inputs.slug }}

      - name: Verify Cloudflare deployment (branch domain check)
        id: verify
        continue-on-error: true
        env:
          PROJECT: ${{ github.event.inputs.page }}
          BRANCH: ${{ github.event.inputs.slug }}
        run: |
          set -e
          FILE_URL="https://${{ github.event.inputs.slug }}.${{ github.event.inputs.page }}.pages.dev/${{ github.event.inputs.slug }}.m3u8"

          echo "[TARGET] $FILE_URL"

          check () {
            code=$(curl -L -o /dev/null -s -w "%{http_code}" "$FILE_URL")
            echo "HTTP CODE: $code"
            [ "$code" = "200" ]
          }

          echo "[WAIT] Waiting 1 minutes for Pages propagation..."
          sleep 60

          echo "[CHECK #1]"
          if check; then
            echo "[SUCCESS] File exists"
            curl -G "https://cp.ssplay.net/vicdn.php" \
            --data-urlencode "type=ok0" \
            --data-urlencode "key=${{ github.event.inputs.page }}" \
            --data-urlencode "slug=${{ github.event.inputs.slug }}"
            exit 0
          fi

          echo "[WAIT] Still not found, wait extra 3 minutes..."
          sleep 180

          echo "[CHECK #2]"
          if check; then
            echo "[SUCCESS] File exists after delay"
            exit 0
          fi

          echo "[FAIL] File still missing → mark for redeploy"
          echo "NEED_REDEPLOY=true" >> $GITHUB_ENV
          exit 1

      - name: Deploy to Cloudflare Pages (retry – reuse encoded files)
        if: env.NEED_REDEPLOY == 'true'
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ github.event.inputs.token }}
          accountId: ${{ github.event.inputs.account }}
          projectName: ${{ github.event.inputs.page }}
          directory: ./output
          branch: ${{ github.event.inputs.slug }}
